name: 🤖 AI Database Optimization

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * 1"  # Runs every Monday at 04:00 UTC

jobs:
  optimize_database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install OpenAI API Client
      run: pip install openai

    - name: Run AI Database Optimizer
      run: python .github/scripts/ai_db_optimizer.py

    - name: Create PR with Optimized Queries
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git checkout -b db-optimization
        git add .
        git commit -m "🤖 AI Database Optimization: Faster Queries & Indexing"
        git push origin db-optimization

    - name: Open Pull Request
      run: gh pr create --title "🤖 AI Optimized Database" --body "AI-powered query optimizations & indexing" --base main --head db-optimization
